Llama-3-1B-OfflineDPO:
  completions_kwargs:
    batch_size: 16
    max_new_tokens: 4096
    model_kwargs:
      dtype: bfloat16
    model_name: /scratch/ssd004/scratch/snajafi/vector-backup/mmpo-experiments/llama3.2-1b-sftdatasetv3-sft-checkpoint-111000-offline-dpo-beta-0.05-lr-1.0e-6/checkpoint-3569_full_model
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.95
    top_p: 0.8
  fn_completions: vllm_local_completions
  pretty_name: Llama-3-1B-OfflineDPO
  prompt_template: Llama-3-1B-OfflineDPO/prompt.txt